config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'
  
  resources :shoes do 
    resources :reviews
  end 

  

  get '/signup', to:'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook'
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :shoe
    belongs_to :user
    
    validates :title, uniqueness: true
    validates :title, :review, presence: true
end

app/models/shoe.rb
class Shoe < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews 
    
    validates :model, uniqueness: true
    validates :model, :brand, presence: true

    scope :ordered_model, -> { order(model: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :shoes, through: :reviews
    
    has_secure_password
    validates :username, :email, uniqueness: true
    validates :username, :email, presence: true
    validates :password, length: {:minimum => 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :current_user, :current_shoe, :logged_in?, :verification
    def new 
        if params[:shoe_id]
            @shoe = Shoe.find_by(id: params[:shoe_id])
            @review = @shoe.reviews.new(user_id: @user.id)
        end
    end

    def create
        @review = @shoe.reviews.create(review_params)
        if @review.valid? 
            @shoe = @review.shoe
            redirect_to shoe_review_path(@shoe, @review)
        else
            render :new
        end
    end

    def edit 
        set_review
        if params[:shoe_id] && current_user.id == @review.user_id 
            current_shoe
        end
    end 

    def update
        set_review
        if @review.update(review_params) && @review.valid?
            redirect_to shoe_review_path(@shoe, @review)
        else 
            render :edit
        end
    end

    def show 
        @review = @shoe.reviews.find_by(id: params[:id])
    end 

    def destroy
        @review = Review.find_by(id: params[:id])
        if params[:shoe_id] && current_user.id == @review.user_id 
            @review.destroy
            redirect_to shoe_path(@shoe)
        end
    end

    private
    
    def review_params
        params.require(:review).permit(:title, :review, :user_id)
    end

    def current_shoe
        @shoe = Shoe.find_by(id: params[:shoe_id])
    end 

    def set_review 
        @review = Review.find_by(id: params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.find_by(:email => params[:email])
        if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to @user
        else
          render :new
        end
      end

      def facebook
        @user = User.find_or_create_by(email: auth['info']['email']) do |u|
          u.username = auth['info']['name']
          u.password = SecureRandom.hex
          end
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      end  

    def destroy
          session.delete :user_id
          redirect_to root_url
    end

    private
 
	def auth
	  request.env['omniauth.auth']
	end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
    before_action :present_shoe, :logged_in?, :verification
    
    def index
        @shoes = Shoe.ordered_model
    end

    def new 
        @shoe = Shoe.new
    end

    def create
        @shoe = Shoe.create(shoe_params)
        if @shoe.valid?
            flash[:notice] = "A New Shoe Has Been Created"
            redirect_to @shoe
        else
            render :new
        end
    end

    def update
        if @shoe.update(shoe_params)
            @shoe.save
            flash[:notice] = "Shoe Entry Has Been Updated"
            redirect_to @shoe
        else
            render :edit
        end
    end

    def destroy
        present_shoe.destroy
        flash[:notice] = "Shoe Entry Has Been Deleted"
        redirect_to shoes_path
    end

    def show
        @reviews = @shoe.reviews 
    end

    private

    def shoe_params
        params.require(:shoe).permit(:model, :brand)
    end

    def present_shoe
        @shoe = Shoe.find_by(id: params[:id])
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in?, :current_user
    
    def new 
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid? 
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
    end


    private

    def user_params
        params.require(:user).permit(:username, :password, :email)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @user = User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!session[:user_id]
    end 

    def verification
        redirect_to '/' unless logged_in?
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsShoeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if logged_in? %>
    <%= link_to "Log out", logout_path, method: :delete %>
    <%= link_to "My Profile", user_path(current_user), method: :get %>
    <%= link_to "All Shoes", shoes_path, method: :get%>
    <% end %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@shoe, @review] do |f| %>
    
    <%= f.hidden_field :user_id, :value => current_user.id%>
    <%= f.label :title %> 
    <%= f.text_field :title%>
    <br>
    <%= f.label :review %> 
    <%= f.text_area :review %>
    
    <br>
    <% if @review.errors.any? %>
    <ul>
      <% @review.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
    
    <br>
    <%= f.submit %>
  <% end %>

app/views/reviews/edit.html.erb
<h1> Edit Review for <%= @shoe.model %> </h1>
<%= render partial: 'form' %> 

app/views/reviews/new.html.erb
<h1> Review for <%= @shoe.model %> </h1>
<%= render partial: 'form' %> 

app/views/reviews/show.html.erb
<h1>About the: <%=@shoe.model%></h1>

<h2><%=@review.title%></h2>
<p><%=@review.review%></p>

<h4>Back to: <%= link_to @shoe.model, shoe_path(@shoe)%><br></h4>

<% if current_user.id == @review.user_id%>
    <%= link_to 'Edit Review', edit_shoe_review_path(@shoe, @review)%><br>
    <%= link_to 'Delete Review', shoe_review_path(@shoe, @review), method: :delete %>
<%end%>

app/views/shoes/_form.html.erb
<%= form_for @shoe do |f| %>
    <%= f.label :model %> 
    <%= f.text_field :model %>
    <br>
    <%= f.label :brand %> 
    <%= f.text_field :brand %>
    
    <br>
    <% if @shoe.errors.any? %>
    <ul>
      <% @shoe.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>

    <br>
    <%= f.submit %>
  <% end %>

app/views/shoes/edit.html.erb
<h1>edit <%=@shoe.model%></h1>
<%= render partial: 'form' %>

app/views/shoes/index.html.erb
<%=flash[:notice]%>

<% @shoes.each do |shoe| %>
    <h3><ul>
    <li> Model: <%= link_to shoe.model, shoe_path(shoe) %> </li>
    <li> Brand: <%= shoe.brand %> </li>
    </ul></h3>
    <br>
<% end %>

<%= link_to "Create New Shoe", new_shoe_path%>

app/views/shoes/new.html.erb
<h1> New Shoe </h1>
<%= render partial: 'form' %>

app/views/shoes/show.html.erb
<h1>The <%=@shoe.model%></h1>
<h3>Brand: <%=@shoe.brand%></h3>

<p> <%=link_to "All Shoes", shoes_path%> </p>



<p><%=link_to "Edit Shoe", edit_shoe_path(@shoe)%></p>
<p><%= link_to "Delete Shoe", shoe_path(@shoe), method: :delete %> </p>



<h4> Shoe Reviews </h4>
<% @reviews.each do |review| %>
        <h4> Title: <%= link_to review.title, shoe_review_path(@shoe, review)%></h4>
    <% end %>
<p> <%= link_to "Write a New Review", new_shoe_review_path(@shoe)%> </p>

app/views/users/new.html.erb
<h1>SIGN UP</h1>

<%= form_for @user do |f| %>
    <%= f.label :username %> 
    <%= f.text_field :username %>
    <br>
    <%= f.label :email %> 
    <%= f.email_field :email %>
    <br>   
    <%= f.label :password %> 
    <%= f.password_field :password %>

    <br>
    <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
    
    <br>
    <%= f.submit %>
  <% end %>

  <%= link_to('Sign Up with Facebook!', '/auth/facebook') %>

app/views/users/show.html.erb
<h1>Welcome <%=@user.username%></h1>

<p>Click on the link above "All Shoes" and add your own reviews to<br> 
already existing shoes, or create a shoe of your own!</p>

<h3>My Shoe Reviews</h3>

<ul><% @user.reviews.each do |review| %>
    <li><%= link_to review.shoe.model, shoe_path(review.shoe)%></li>
<% end %>
</ul>
   